module.exports = {
	key:'Order',
	name:'order',
	fields:['id',
			'order_status',//订单状态 
			'payment_status',//支付状态
			'shipping_status',//配送状态
			'amount_paid',//已付金额
			'area_name',//地区名称
			'consignee',//收获人
			'memo',//附言
			'phone',//电话
			'point',//赠送积分
			'sn',//订单状态
			'member_id',//会员id
			'open_id',//openId
			'delete_flag',//删除标志
			'create_date'//创建日期
	]
};
