module.exports = {
	key:'Product',
	name:'product',
	fields:['id',
			'sn',//商品编码
			'allocated_stock',//已分配库存
			'cost',//成本价
			'full_name',//全称
			'image',//展示图片
			'weight',//重量（克）
			'introduction',//介绍
			'is_marketable',//是否上架
			'is_top',//是否置顶
			'is_list',//是否列出
			'market_price',//市场价
			'name',//名称
			'point',//赠送积分
			'price',//销售价
			'stock',//库存
			'unit',//单位
			'brand_id',//商品
			'memo',//备注
			'product_category_id']//商品分类
};
